"""initial_schema

Revision ID: d19e33f48bc9
Revises: 
Create Date: 2026-03-20 16:16:34.829301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd19e33f48bc9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_created', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('endpoints',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('endpoint_type', sa.String(length=20), nullable=False),
    sa.Column('algorithm', sa.String(length=20), nullable=False),
    sa.Column('key_length', sa.Integer(), nullable=False),
    sa.Column('data_sensitivity', sa.Integer(), nullable=False),
    sa.Column('exposure_surface', sa.String(length=20), nullable=False),
    sa.Column('traffic_volume', sa.String(length=20), nullable=False),
    sa.Column('cert_expiry_days', sa.Integer(), nullable=False),
    sa.Column('risk_tier', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('migration_status', sa.String(length=20), nullable=False),
    sa.Column('migrated_algorithm', sa.String(length=50), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_endpoints_algorithm', 'endpoints', ['algorithm'], unique=False)
    op.create_index('idx_endpoints_migration_status', 'endpoints', ['migration_status'], unique=False)
    op.create_index('idx_endpoints_risk_tier', 'endpoints', ['risk_tier'], unique=False)
    op.create_table('model_evaluations',
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('binary_class', sa.String(length=20), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('precision_score', sa.Float(), nullable=False),
    sa.Column('recall', sa.Float(), nullable=False),
    sa.Column('f1_score', sa.Float(), nullable=False),
    sa.Column('training_samples', sa.Integer(), nullable=False),
    sa.Column('test_samples', sa.Integer(), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_jobs',
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('migration_configs',
    sa.Column('endpoint_id', sa.UUID(), nullable=False),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('config_text', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_migration_configs_endpoint', 'migration_configs', ['endpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_migration_configs_endpoint', table_name='migration_configs')
    op.drop_table('migration_configs')
    op.drop_table('users')
    op.drop_table('scan_jobs')
    op.drop_table('model_evaluations')
    op.drop_index('idx_endpoints_risk_tier', table_name='endpoints')
    op.drop_index('idx_endpoints_migration_status', table_name='endpoints')
    op.drop_index('idx_endpoints_algorithm', table_name='endpoints')
    op.drop_table('endpoints')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
